# Generated by Django 2.0 on 2017-12-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aliases',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(db_column='alias', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('match_id', models.AutoField(db_column='match_id', primary_key=True, serialize=False)),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='placings',
            fields=[
                ('placing_id', models.AutoField(db_column='placing_id', primary_key=True, serialize=False)),
                ('placing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('player_id', models.AutoField(db_column='player_id', primary_key=True, serialize=False)),
                ('elo', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tournaments',
            fields=[
                ('tourney_id', models.AutoField(db_column='tourney_id', primary_key=True, serialize=False)),
                ('date_started', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='placings',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='display.players'),
        ),
        migrations.AddField(
            model_name='placings',
            name='tourney_id',
            field=models.ForeignKey(db_column='tourney_id', on_delete=django.db.models.deletion.CASCADE, to='display.tournaments'),
        ),
        migrations.AddField(
            model_name='matches',
            name='loser_id',
            field=models.ForeignKey(db_column='loser_id', on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='display.players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='tourney_id',
            field=models.ForeignKey(db_column='tourney_id', on_delete=django.db.models.deletion.CASCADE, to='display.tournaments'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner_id',
            field=models.ForeignKey(db_column='winner_id', on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='display.players'),
        ),
    ]
