# Generated by Django 2.0 on 2017-12-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placings',
            options={'ordering': ['tourney_id__date_started']},
        ),
        migrations.AlterModelOptions(
            name='tournaments',
            options={'ordering': ['date_started']},
        ),
    ]
